{{- $certString := include "regcred-injector.gen-certs" . -}}
{{- $certList := split "$" $certString -}}
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
    name:  {{ include "regcred-injector.fullname" . }}
webhooks:
- name: {{ include "regcred-injector.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  matchPolicy: Equivalent
  objectSelector:
    matchExpressions:
    - key: "app.kubernetes.io/component"
      operator: NotIn
      values: ["regcred-injector"]
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    scope: "Namespaced"
  clientConfig:
    service:
      namespace: "{{ .Release.Namespace }}"
      name: "{{ include "regcred-injector.fullname" . }}"
      path: "/admission"
      port: 8443
    caBundle: {{ $certList._2 }}
  admissionReviewVersions: ["v1beta1"]
  failurePolicy: Ignore
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "regcred-injector.fullname" . }}
  labels:
    {{ include "regcred-injector.labels" . | nindent 4 }}
data:
  cert: {{ $certList._0 }}
  key: {{ $certList._1 }}
  password: {{ .Values.docker.password | b64enc }}
