{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "regcred-injector.serviceAccountName" . }}
  labels:
    {{- include "regcred-injector.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "regcred-injector.fullname" . }}
  labels:
    {{- include "regcred-injector.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create"]  
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: ClusterRoleBinding
metadata:
  name: {{ include "regcred-injector.fullname" . }}
  namespace: default
  labels:
    {{- include "regcred-injector.labels" . | nindent 4 }}
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: {{ include "regcred-injector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole 
  name: {{ include "regcred-injector.fullname" . }} # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
  